services:
  node1:
    container_name: node1
    image: bitcoinsv/bitcoin-sv:1.1.0
    ports:
      - "18332:18332" # RPC port
      - "28332:28332"
    expose:
      - "18332"
      - "18333"
      - "28332"
    volumes:
      - ./bitcoin.conf:/data/bitcoin.conf
      - node1-test-data:/data
    networks:
      - net1
    command: [ "/entrypoint.sh", "bitcoind", "-connect=node2:18333" ]

  node2:
    container_name: node2
    image: bitcoinsv/bitcoin-sv:1.1.0
    ports:
      - "48332:18332"
      - "38332:28332"
    expose:
      - "18332"
      - "18333"
    healthcheck:
      test: [ "CMD", "/entrypoint.sh", "bitcoin-cli", "getinfo" ]
    volumes:
      - ./bitcoin.conf:/data/bitcoin.conf
      - node2-test-data:/data
    networks:
      - net2
    command: [ "/entrypoint.sh", "bitcoind", "-connect=node1:18333" ]

volumes:
  node1-test-data:
  node2-test-data:

networks:
  net1:
  net2:
